### ISSUE TITLE
input has argument of a shape

### ISSUE THREAD

**Issue by Cdriko** [shader-park/shader-park-core#74]
I made a shape like that : 

```
var AlB2=shape((R)=>{
  var t=R*0.667;
  var Z=sqrt((R*R)+ (2*R*t)-3* (t*t));
  
	displace(3*t,t*Racine3,Z);
  sphere(R);
}

```

If I call it with a numerical argument it's ok, but if I use an input, it fails and don't render.

Take a look at https://shaderpark.com/sculpture/-N0_-mG9uWF-OuYurpSx for the complete code

**Comment by PWhiddy** [comment]
Hey, thanks for reporting this! 
The reason that's happing is a missing feature/bug on our end. @torinmb and I are working on a fix.
The issue is actually line 45:
```
displace(-t,t*Racine3,0.);
```
Until a fix is out, you can't negate a non-primitive variable. Subtraction works fine, but the negative can't go in front by itself.
Fortunately there is an easy work around you can use before the fix is out, just do `-1*variable` instead of `-variable`.
So if you change line 45 to:
```
displace(-1*t,t*Racine3,0.);
```
